[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0ATkoCc7ZiV2kaSHnubBKaJ-KrKxNDtK4Pb_sCxKc4Pl72pKsoLouGvXrFhfMA8ICXfaxQeQuQE71xBCxPzwfrjKFxaqIzi3uI70LZC0KS3s1mnhkdyXZ_FnDxotQ3EQ_jSlYxSLEKo5cvj9J7HF2dN_CRoGyqibCHfWpn5eIvGq4Eq3z7o9vt47Q78yqREbxYS5QGYsaCgYKAQYSARcSFQHGX2MiWMQQNb0hfTyBDnu_qKN0oQ0206","token_type":"Bearer","refresh_token":"1//034Cmg8eyjJewCgYIARAAGAMSNwF-L9Ira6tBocgsH-fs3mFzna9lYN4oAFauudUvTKcUI3c20HrmjxjyT3_0kWZcughBghWxGy0","expiry":"2026-02-22T11:02:40.185910564+01:00","expires_in":3599}
team_drive = 

